from test2 import service
import requests
import json
# from test import similar

with open("rolex_clean_data.json", "r", encoding="utf-8") as f:
    products = json.load(f)
    
seen = set()   # faster lookup
unique_ids = []

for item in products:
    pid = item.get("product_id")

    if pid and pid not in seen:
        seen.add(pid)
        unique_ids.append(pid)

#  write as text
with open("reference.txt", "w", encoding="utf-8") as f:
    for pid in unique_ids:
        f.write(pid + "\n")

print(" Done! Total unique product_ids:", len(unique_ids))

url = "https://i-chrono.com/api/Import-products-vector"

products = requests.get(url).json()
# products =[{'product_id': 'Ref 224270',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m224270-0001',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 1},
#  {'product_id': 'Ref 224270',
#   'image': 'https://img.chrono24.com/images/uhren/45606778-jiyqranyozafb7avqkg0enu7-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 2},
#  {'product_id': 'Ref 224270',
#   'image': 'https://img.chrono24.com/images/uhren/45606778-m0kl7jpctli23xfzlxghbm40-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 3},
#  {'product_id': 'Ref 224270',
#   'image': 'https://img.chrono24.com/images/uhren/45760091-sanyan3hisix3je8rxc32j4f-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 4},
#  {'product_id': 'Ref 224270',
#   'image': 'https://img.chrono24.com/images/uhren/45760091-mmg8wli1ivk2o0czxejiwt8k-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 5},
#  {'product_id': 'Ref 224270',
#   'image': 'https://img.chrono24.com/images/uhren/41471739-zddxan940s15fngoixhqxh1n-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 6},
#  {'product_id': 'Ref 224270',
#   'image': 'https://cdn2.ethoswatches.com/rolex/pub/media/catalog/product/cache/a68df29a9e2afb500a8d2ce09034894d/m/1/m126622-0001-feature-3_1.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '40MM',
#   'id': 7},
#  {'product_id': '126622Ref ',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126622-0001',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 8},
#  {'product_id': '126622Ref ',
#   'image': 'https://cdn2.ethoswatches.com/rolex/pub/media/catalog/product/cache/a68df29a9e2afb500a8d2ce09034894d/m/1/m126622-0001-multiple-4.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 9},
#  {'product_id': '126622Ref ',
#   'image': 'https://img.chrono24.com/images/uhren/45281594-ftcm3sgi5g09c1gll82kxg89-ExtraLarge.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 10},
#  {'product_id': '126622Ref ',
#   'image': 'https://img.chrono24.com/images/uhren/45281594-4bizpiqb75cmfsjujumdhew6-ExtraLarge.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 11},
#  {'product_id': '126622Ref ',
#   'image': 'https://img.chrono24.com/images/uhren/45281594-pemg2ni0qq2dclhglwxxgdb5-ExtraLarge.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 12},
#  {'product_id': '126622Ref ',
#   'image': 'https://shine-watches.com/wp-content/uploads/2022/07/Rolex-Yacht-Master-40mm-Oyster-Ref.-M116622-007.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 13},
#  {'product_id': '126622Ref ',
#   'image': 'https://shine-watches.com/wp-content/uploads/2022/07/Rolex-Yacht-Master-40mm-Oyster-Ref.-M116622-005.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 14},
#  {'product_id': '126622Ref ',
#   'image': 'https://shine-watches.com/wp-content/uploads/2022/07/Rolex-Yacht-Master-40mm-Oyster-Ref.-M116622-007.jpg',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 15},
#  {'product_id': '126622Ref ',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-main-configurator/c_limit,w_1920/v1/catalogue/2025/configurator/raw-dial-with-shadow/51789_g_40',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 16},
#  {'product_id': '126622Ref ',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-main-configurator/c_limit,w_1920/v1/catalogue/2025/configurator/raw-dial-with-shadow/51579_g_40',
#   'colour': 'Bright Blue, Slate',
#   'material': 'Platinum',
#   'diameter': '40MM',
#   'id': 17},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://img.chrono24.com/images/uhren/45228361-ff3kyh99nmuif5d6xjz28gau-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 18},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://img.chrono24.com/images/uhren/45228361-zqn54f24gx6jzdsw4xu3m2in-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 19},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://img.chrono24.com/images/uhren/45228361-rdd9n9aecme997lx4fqc2r5y-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 20},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://img.chrono24.com/images/uhren/45228361-k3b3u6j6yig6auh8c1hj4mfy-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 21},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-majesty/c_limit,w_640/v1/catalogue/2025/upright-c/m124270-0001',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 22},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://img.chrono24.com/images/uhren/45228361-cxkis14v6qffk4wnjkvbtlge-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 23},
#  {'product_id': 'Ref - 14270',
#   'image': 'https://img.chrono24.com/images/uhren/45228361-gkgb44ws5hl44nrahmm7b94c-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 24},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0002',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 25},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0005',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 26},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0024',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 27},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0017',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 28},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0023',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 29},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0008',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 30},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0001',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 31},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0018',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 32},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0006',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 33},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0007',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 34},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0003',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 35},
#  {'product_id': 'Ref 126200',
#   'image': 'https://media.rolex.com/image/upload/q_auto/f_auto/t_v7-cover-majesty-landscape/c_limit,w_1920/v1/catalogue/2025/upright-c/m126200-0004',
#   'colour': 'Silver,Bright blue, Mint green, Slate, White, Silver, Bright black',
#   'material': 'Oystersteel',
#   'diameter': '36MM',
#   'id': 36},
#  {'product_id': 'Ref - 4072',
#   'image': 'https://img.chrono24.com/images/uhren/44544366-uzd0davo0sxkd74zdo4aoq2l-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Steel',
#   'diameter': '40MM',
#   'id': 37},
#  {'product_id': 'Ref - 4072',
#   'image': 'https://img.chrono24.com/images/uhren/44544366-fyhl6vl1q0weaokkcbb5dtm8-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Steel',
#   'diameter': '40MM',
#   'id': 38},
#  {'product_id': 'Ref - 4072',
#   'image': 'https://img.chrono24.com/images/uhren/44544366-z3ushzi9qo8rubynr85og44n-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Steel',
#   'diameter': '40MM',
#   'id': 39},
#  {'product_id': 'Ref - 4072',
#   'image': 'https://img.chrono24.com/images/uhren/ipy9dhcr962w-5p90hm72t7k34dzaa33oyyhk-ExtraLarge.jpg',
#   'colour': 'Black',
#   'material': 'Steel',
#   'diameter': '40MM',
#   'id': 40},
#   {'product_id': '278285RBR',
#   'image': 'https://d5ee3ksv7elb9.cloudfront.net/products/77f04ebc-7eb1-401e-9ec2-029381a347ac.png',
#   'colour': 'Black',
#   'material': 'Steel',
#   'diameter': '40MM',
#   'id': 40},
#  ]

print(len(products))

# input_url = "https://d5ee3ksv7elb9.cloudfront.net/product/0eb1f10b-53ad-4e68-ac8a-0ee268775875.png"
service.build(products)
# service.save()